version: '3.8'
services:
  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command:
      - "--verbose"
      - "--global-response-templating"
      - "--enable-browser-proxying"